<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20210920161027 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE image (id INT AUTO_INCREMENT NOT NULL, image_name_id INT DEFAULT NULL, image_url VARCHAR(255) NOT NULL, UNIQUE INDEX UNIQ_C53D045FE407CB0A (image_name_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE skill (id INT AUTO_INCREMENT NOT NULL, skill_name VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('ALTER TABLE image ADD CONSTRAINT FK_C53D045FE407CB0A FOREIGN KEY (image_name_id) REFERENCES skill (id)');
        $this->addSql('ALTER TABLE ac_activities CHANGE context context JSON NOT NULL, CHANGE batch batch VARCHAR(191) DEFAULT NULL, CHANGE payload payload JSON DEFAULT NULL, CHANGE resourceLocale resourceLocale VARCHAR(191) DEFAULT NULL, CHANGE resourceWebspaceKey resourceWebspaceKey VARCHAR(191) DEFAULT NULL, CHANGE resourceTitle resourceTitle VARCHAR(191) DEFAULT NULL, CHANGE resourceTitleLocale resourceTitleLocale VARCHAR(191) DEFAULT NULL, CHANGE resourceSecurityContext resourceSecurityContext VARCHAR(191) DEFAULT NULL, CHANGE resourceSecurityObjectType resourceSecurityObjectType VARCHAR(191) DEFAULT NULL, CHANGE resourceSecurityObjectId resourceSecurityObjectId VARCHAR(191) DEFAULT NULL, CHANGE userId userId INT DEFAULT NULL');
        $this->addSql('ALTER TABLE ca_categories CHANGE category_key category_key VARCHAR(191) DEFAULT NULL, CHANGE idCategoriesParent idCategoriesParent INT DEFAULT NULL, CHANGE idUsersCreator idUsersCreator INT DEFAULT NULL, CHANGE idUsersChanger idUsersChanger INT DEFAULT NULL');
        $this->addSql('ALTER TABLE ca_category_meta CHANGE locale locale VARCHAR(5) DEFAULT NULL');
        $this->addSql('ALTER TABLE ca_category_translations CHANGE idUsersCreator idUsersCreator INT DEFAULT NULL, CHANGE idUsersChanger idUsersChanger INT DEFAULT NULL');
        $this->addSql('ALTER TABLE ca_keywords CHANGE idUsersCreator idUsersCreator INT DEFAULT NULL, CHANGE idUsersChanger idUsersChanger INT DEFAULT NULL');
        $this->addSql('ALTER TABLE co_account_contacts CHANGE idPositions idPositions INT DEFAULT NULL');
        $this->addSql('ALTER TABLE co_accounts CHANGE logo logo INT DEFAULT NULL, CHANGE externalId externalId VARCHAR(255) DEFAULT NULL, CHANGE number number VARCHAR(255) DEFAULT NULL, CHANGE corporation corporation VARCHAR(255) DEFAULT NULL, CHANGE uid uid VARCHAR(50) DEFAULT NULL, CHANGE registerNumber registerNumber VARCHAR(255) DEFAULT NULL, CHANGE placeOfJurisdiction placeOfJurisdiction VARCHAR(255) DEFAULT NULL, CHANGE mainEmail mainEmail VARCHAR(255) DEFAULT NULL, CHANGE mainPhone mainPhone VARCHAR(255) DEFAULT NULL, CHANGE mainFax mainFax VARCHAR(255) DEFAULT NULL, CHANGE mainUrl mainUrl VARCHAR(255) DEFAULT NULL, CHANGE idContactsMain idContactsMain INT DEFAULT NULL, CHANGE idAccountsParent idAccountsParent INT DEFAULT NULL, CHANGE idUsersCreator idUsersCreator INT DEFAULT NULL, CHANGE idUsersChanger idUsersChanger INT DEFAULT NULL');
        $this->addSql('ALTER TABLE co_addresses CHANGE title title VARCHAR(250) DEFAULT NULL, CHANGE primaryAddress primaryAddress TINYINT(1) DEFAULT NULL, CHANGE deliveryAddress deliveryAddress TINYINT(1) DEFAULT NULL, CHANGE billingAddress billingAddress TINYINT(1) DEFAULT NULL, CHANGE street street VARCHAR(150) DEFAULT NULL, CHANGE number number VARCHAR(60) DEFAULT NULL, CHANGE addition addition VARCHAR(60) DEFAULT NULL, CHANGE zip zip VARCHAR(60) DEFAULT NULL, CHANGE city city VARCHAR(60) DEFAULT NULL, CHANGE state state VARCHAR(60) DEFAULT NULL, CHANGE countryCode countryCode VARCHAR(5) DEFAULT NULL, CHANGE postboxNumber postboxNumber VARCHAR(100) DEFAULT NULL, CHANGE postboxPostcode postboxPostcode VARCHAR(100) DEFAULT NULL, CHANGE postboxCity postboxCity VARCHAR(100) DEFAULT NULL, CHANGE latitude latitude DOUBLE PRECISION DEFAULT NULL, CHANGE longitude longitude DOUBLE PRECISION DEFAULT NULL');
        $this->addSql('ALTER TABLE co_bank_account CHANGE bankName bankName VARCHAR(150) DEFAULT NULL, CHANGE bic bic VARCHAR(100) DEFAULT NULL');
        $this->addSql('ALTER TABLE co_contacts CHANGE avatar avatar INT DEFAULT NULL, CHANGE middleName middleName VARCHAR(60) DEFAULT NULL, CHANGE birthday birthday DATE DEFAULT NULL, CHANGE salutation salutation VARCHAR(255) DEFAULT NULL, CHANGE formOfAddress formOfAddress INT DEFAULT NULL, CHANGE newsletter newsletter TINYINT(1) DEFAULT NULL, CHANGE gender gender VARCHAR(1) DEFAULT NULL, CHANGE mainEmail mainEmail VARCHAR(255) DEFAULT NULL, CHANGE mainPhone mainPhone VARCHAR(255) DEFAULT NULL, CHANGE mainFax mainFax VARCHAR(255) DEFAULT NULL, CHANGE mainUrl mainUrl VARCHAR(255) DEFAULT NULL, CHANGE idTitles idTitles INT DEFAULT NULL, CHANGE idUsersCreator idUsersCreator INT DEFAULT NULL, CHANGE idUsersChanger idUsersChanger INT DEFAULT NULL');
        $this->addSql('ALTER TABLE me_collection_types CHANGE collection_type_key collection_type_key VARCHAR(191) DEFAULT NULL');
        $this->addSql('ALTER TABLE me_collections CHANGE style style VARCHAR(255) DEFAULT NULL, CHANGE collection_key collection_key VARCHAR(191) DEFAULT NULL, CHANGE idCollectionsMetaDefault idCollectionsMetaDefault INT DEFAULT NULL, CHANGE idCollectionsParent idCollectionsParent INT DEFAULT NULL, CHANGE idUsersCreator idUsersCreator INT DEFAULT NULL, CHANGE idUsersChanger idUsersChanger INT DEFAULT NULL');
        $this->addSql('ALTER TABLE me_file_version_content_languages CHANGE idFileVersions idFileVersions INT DEFAULT NULL');
        $this->addSql('ALTER TABLE me_file_version_publish_languages CHANGE idFileVersions idFileVersions INT DEFAULT NULL');
        $this->addSql('ALTER TABLE me_file_versions CHANGE mimeType mimeType VARCHAR(191) DEFAULT NULL, CHANGE properties properties VARCHAR(1000) DEFAULT NULL, CHANGE focusPointX focusPointX INT DEFAULT NULL, CHANGE focusPointY focusPointY INT DEFAULT NULL, CHANGE idFileVersionsMetaDefault idFileVersionsMetaDefault INT DEFAULT NULL, CHANGE idFiles idFiles INT DEFAULT NULL, CHANGE idUsersCreator idUsersCreator INT DEFAULT NULL, CHANGE idUsersChanger idUsersChanger INT DEFAULT NULL');
        $this->addSql('ALTER TABLE me_files CHANGE idUsersCreator idUsersCreator INT DEFAULT NULL, CHANGE idUsersChanger idUsersChanger INT DEFAULT NULL');
        $this->addSql('ALTER TABLE me_media CHANGE idPreviewImage idPreviewImage INT DEFAULT NULL, CHANGE idUsersCreator idUsersCreator INT DEFAULT NULL, CHANGE idUsersChanger idUsersChanger INT DEFAULT NULL');
        $this->addSql('ALTER TABLE ro_routes CHANGE target_id target_id INT DEFAULT NULL, CHANGE idUsersCreator idUsersCreator INT DEFAULT NULL, CHANGE idUsersChanger idUsersChanger INT DEFAULT NULL');
        $this->addSql('ALTER TABLE se_groups CHANGE idGroupsParent idGroupsParent INT DEFAULT NULL, CHANGE idUsersCreator idUsersCreator INT DEFAULT NULL, CHANGE idUsersChanger idUsersChanger INT DEFAULT NULL');
        $this->addSql('ALTER TABLE se_permissions CHANGE module module VARCHAR(60) DEFAULT NULL, CHANGE idRoles idRoles INT DEFAULT NULL');
        $this->addSql('ALTER TABLE se_role_settings CHANGE roleId roleId INT DEFAULT NULL');
        $this->addSql('ALTER TABLE se_roles CHANGE role_key role_key VARCHAR(60) DEFAULT NULL, CHANGE idSecurityTypes idSecurityTypes INT DEFAULT NULL, CHANGE idUsersCreator idUsersCreator INT DEFAULT NULL, CHANGE idUsersChanger idUsersChanger INT DEFAULT NULL');
        $this->addSql('ALTER TABLE se_user_groups CHANGE idGroups idGroups INT DEFAULT NULL, CHANGE idUsers idUsers INT DEFAULT NULL');
        $this->addSql('ALTER TABLE se_user_roles CHANGE idUsers idUsers INT DEFAULT NULL, CHANGE idRoles idRoles INT DEFAULT NULL');
        $this->addSql('ALTER TABLE se_users CHANGE lastLogin lastLogin DATETIME DEFAULT NULL, CHANGE confirmationKey confirmationKey VARCHAR(128) DEFAULT NULL, CHANGE passwordResetToken passwordResetToken VARCHAR(80) DEFAULT NULL, CHANGE passwordResetTokenExpiresAt passwordResetTokenExpiresAt DATETIME DEFAULT NULL, CHANGE privateKey privateKey VARCHAR(2000) DEFAULT NULL, CHANGE apiKey apiKey CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', CHANGE email email VARCHAR(191) DEFAULT NULL, CHANGE idUsersCreator idUsersCreator INT DEFAULT NULL, CHANGE idUsersChanger idUsersChanger INT DEFAULT NULL');
        $this->addSql('ALTER TABLE ta_tags CHANGE idUsersCreator idUsersCreator INT DEFAULT NULL, CHANGE idUsersChanger idUsersChanger INT DEFAULT NULL');
        $this->addSql('ALTER TABLE phpcr_nodes CHANGE sort_order sort_order INT DEFAULT NULL');
        $this->addSql('ALTER TABLE phpcr_type_nodes CHANGE primary_item primary_item VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE phpcr_type_props CHANGE default_value default_value VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE phpcr_type_childs CHANGE default_type default_type VARCHAR(255) DEFAULT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE image DROP FOREIGN KEY FK_C53D045FE407CB0A');
        $this->addSql('DROP TABLE image');
        $this->addSql('DROP TABLE skill');
        $this->addSql('ALTER TABLE ac_activities CHANGE context context LONGTEXT CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_bin`, CHANGE batch batch VARCHAR(191) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE payload payload LONGTEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_bin`, CHANGE resourceLocale resourceLocale VARCHAR(191) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE resourceWebspaceKey resourceWebspaceKey VARCHAR(191) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE resourceTitle resourceTitle VARCHAR(191) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE resourceTitleLocale resourceTitleLocale VARCHAR(191) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE resourceSecurityContext resourceSecurityContext VARCHAR(191) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE resourceSecurityObjectType resourceSecurityObjectType VARCHAR(191) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE resourceSecurityObjectId resourceSecurityObjectId VARCHAR(191) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE userId userId INT DEFAULT NULL');
        $this->addSql('ALTER TABLE ca_categories CHANGE category_key category_key VARCHAR(191) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE idCategoriesParent idCategoriesParent INT DEFAULT NULL, CHANGE idUsersCreator idUsersCreator INT DEFAULT NULL, CHANGE idUsersChanger idUsersChanger INT DEFAULT NULL');
        $this->addSql('ALTER TABLE ca_category_meta CHANGE locale locale VARCHAR(5) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE ca_category_translations CHANGE idUsersCreator idUsersCreator INT DEFAULT NULL, CHANGE idUsersChanger idUsersChanger INT DEFAULT NULL');
        $this->addSql('ALTER TABLE ca_keywords CHANGE idUsersCreator idUsersCreator INT DEFAULT NULL, CHANGE idUsersChanger idUsersChanger INT DEFAULT NULL');
        $this->addSql('ALTER TABLE co_account_contacts CHANGE idPositions idPositions INT DEFAULT NULL');
        $this->addSql('ALTER TABLE co_accounts CHANGE logo logo INT DEFAULT NULL, CHANGE externalId externalId VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE number number VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE corporation corporation VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE uid uid VARCHAR(50) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE registerNumber registerNumber VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE placeOfJurisdiction placeOfJurisdiction VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE mainEmail mainEmail VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE mainPhone mainPhone VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE mainFax mainFax VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE mainUrl mainUrl VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE idContactsMain idContactsMain INT DEFAULT NULL, CHANGE idAccountsParent idAccountsParent INT DEFAULT NULL, CHANGE idUsersCreator idUsersCreator INT DEFAULT NULL, CHANGE idUsersChanger idUsersChanger INT DEFAULT NULL');
        $this->addSql('ALTER TABLE co_addresses CHANGE title title VARCHAR(250) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE primaryAddress primaryAddress TINYINT(1) DEFAULT \'NULL\', CHANGE deliveryAddress deliveryAddress TINYINT(1) DEFAULT \'NULL\', CHANGE billingAddress billingAddress TINYINT(1) DEFAULT \'NULL\', CHANGE street street VARCHAR(150) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE number number VARCHAR(60) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE addition addition VARCHAR(60) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE zip zip VARCHAR(60) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE city city VARCHAR(60) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE state state VARCHAR(60) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE countryCode countryCode VARCHAR(5) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE postboxNumber postboxNumber VARCHAR(100) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE postboxPostcode postboxPostcode VARCHAR(100) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE postboxCity postboxCity VARCHAR(100) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE latitude latitude DOUBLE PRECISION DEFAULT \'NULL\', CHANGE longitude longitude DOUBLE PRECISION DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE co_bank_account CHANGE bankName bankName VARCHAR(150) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE bic bic VARCHAR(100) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE co_contacts CHANGE avatar avatar INT DEFAULT NULL, CHANGE middleName middleName VARCHAR(60) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE birthday birthday DATE DEFAULT \'NULL\', CHANGE salutation salutation VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE formOfAddress formOfAddress INT DEFAULT NULL, CHANGE newsletter newsletter TINYINT(1) DEFAULT \'NULL\', CHANGE gender gender VARCHAR(1) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE mainEmail mainEmail VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE mainPhone mainPhone VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE mainFax mainFax VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE mainUrl mainUrl VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE idTitles idTitles INT DEFAULT NULL, CHANGE idUsersCreator idUsersCreator INT DEFAULT NULL, CHANGE idUsersChanger idUsersChanger INT DEFAULT NULL');
        $this->addSql('ALTER TABLE me_collection_types CHANGE collection_type_key collection_type_key VARCHAR(191) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE me_collections CHANGE style style VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE collection_key collection_key VARCHAR(191) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE idCollectionsMetaDefault idCollectionsMetaDefault INT DEFAULT NULL, CHANGE idCollectionsParent idCollectionsParent INT DEFAULT NULL, CHANGE idUsersCreator idUsersCreator INT DEFAULT NULL, CHANGE idUsersChanger idUsersChanger INT DEFAULT NULL');
        $this->addSql('ALTER TABLE me_file_version_content_languages CHANGE idFileVersions idFileVersions INT DEFAULT NULL');
        $this->addSql('ALTER TABLE me_file_version_publish_languages CHANGE idFileVersions idFileVersions INT DEFAULT NULL');
        $this->addSql('ALTER TABLE me_file_versions CHANGE mimeType mimeType VARCHAR(191) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE properties properties VARCHAR(1000) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE focusPointX focusPointX INT DEFAULT NULL, CHANGE focusPointY focusPointY INT DEFAULT NULL, CHANGE idFileVersionsMetaDefault idFileVersionsMetaDefault INT DEFAULT NULL, CHANGE idFiles idFiles INT DEFAULT NULL, CHANGE idUsersCreator idUsersCreator INT DEFAULT NULL, CHANGE idUsersChanger idUsersChanger INT DEFAULT NULL');
        $this->addSql('ALTER TABLE me_files CHANGE idUsersCreator idUsersCreator INT DEFAULT NULL, CHANGE idUsersChanger idUsersChanger INT DEFAULT NULL');
        $this->addSql('ALTER TABLE me_media CHANGE idPreviewImage idPreviewImage INT DEFAULT NULL, CHANGE idUsersCreator idUsersCreator INT DEFAULT NULL, CHANGE idUsersChanger idUsersChanger INT DEFAULT NULL');
        $this->addSql('ALTER TABLE phpcr_nodes CHANGE sort_order sort_order INT DEFAULT NULL');
        $this->addSql('ALTER TABLE phpcr_type_childs CHANGE default_type default_type VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE phpcr_type_nodes CHANGE primary_item primary_item VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE phpcr_type_props CHANGE default_value default_value VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE ro_routes CHANGE target_id target_id INT DEFAULT NULL, CHANGE idUsersCreator idUsersCreator INT DEFAULT NULL, CHANGE idUsersChanger idUsersChanger INT DEFAULT NULL');
        $this->addSql('ALTER TABLE se_groups CHANGE idGroupsParent idGroupsParent INT DEFAULT NULL, CHANGE idUsersCreator idUsersCreator INT DEFAULT NULL, CHANGE idUsersChanger idUsersChanger INT DEFAULT NULL');
        $this->addSql('ALTER TABLE se_permissions CHANGE module module VARCHAR(60) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE idRoles idRoles INT DEFAULT NULL');
        $this->addSql('ALTER TABLE se_role_settings CHANGE roleId roleId INT DEFAULT NULL');
        $this->addSql('ALTER TABLE se_roles CHANGE role_key role_key VARCHAR(60) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE idSecurityTypes idSecurityTypes INT DEFAULT NULL, CHANGE idUsersCreator idUsersCreator INT DEFAULT NULL, CHANGE idUsersChanger idUsersChanger INT DEFAULT NULL');
        $this->addSql('ALTER TABLE se_user_groups CHANGE idGroups idGroups INT DEFAULT NULL, CHANGE idUsers idUsers INT DEFAULT NULL');
        $this->addSql('ALTER TABLE se_user_roles CHANGE idUsers idUsers INT DEFAULT NULL, CHANGE idRoles idRoles INT DEFAULT NULL');
        $this->addSql('ALTER TABLE se_users CHANGE lastLogin lastLogin DATETIME DEFAULT \'NULL\', CHANGE confirmationKey confirmationKey VARCHAR(128) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE passwordResetToken passwordResetToken VARCHAR(80) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE passwordResetTokenExpiresAt passwordResetTokenExpiresAt DATETIME DEFAULT \'NULL\', CHANGE privateKey privateKey VARCHAR(2000) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE apiKey apiKey CHAR(36) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci` COMMENT \'(DC2Type:guid)\', CHANGE email email VARCHAR(191) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE idUsersCreator idUsersCreator INT DEFAULT NULL, CHANGE idUsersChanger idUsersChanger INT DEFAULT NULL');
        $this->addSql('ALTER TABLE ta_tags CHANGE idUsersCreator idUsersCreator INT DEFAULT NULL, CHANGE idUsersChanger idUsersChanger INT DEFAULT NULL');
    }
}
